brand:
  name: Anitha Rathod
menu-string: Menu

nav:
  - title: Books
    url: '#portfolio'
  - title: About Me
    url: '#about'
  - title: Author Visits
    url: '#visit'
  - title: Downloads
    url: '#downloads'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Anitha Rathod 2018

social-buttons:
  - icon: fa fa-amazon
    url: 'http://amazon.com/author/anitharathod'
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/anithagrathod/'
  - icon: fa fa-linkedin
    url: 'https://in.linkedin.com/in/anitha-rathod-84a3099'

quicklinks:
  #- title: Privacy Policy
  #  url: '#'
  #- title: Terms of Use
  #  url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
